sources:
  - name: Planes
    handler:
      graphql:
        source: './schema.graphql'
        endpoint: '{env.ENGINE_URL}/graphql'
        schemaHeaders: 
          Authorization: "{env.SECRET_TOKEN}"
        operationHeaders:
          Authorization: "{env.SECRET_TOKEN}"
