sources:
  - name: Planes
    handler:
      graphql:
        endpoint: http://localhost:3004/graphql
        schemaHeaders: 
          Authorization: "{env.SECRET_TOKEN}"
        operationHeaders:
          Authorization: "{env.SECRET_TOKEN}"
